# Generated by Django 4.0.3 on 2023-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_customerdetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='accno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
