# Generated by Django 4.0.3 on 2023-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_remove_customerdetails_id_customerdetails_accno'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('debamt', models.IntegerField()),
                ('cramt', models.IntegerField()),
                ('acbal', models.IntegerField()),
            ],
        ),
    ]
