# Generated by Django 4.0.3 on 2023-05-17 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='acbal',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='cramt',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='debamt',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='name',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='date_trans',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='reciever',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='sender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
